version: "3.9"
services:
  rust01-api:
    depends_on:
      - rust01-db
    ports:
      - 9090:8000
    build:
      context: .
      target: dev
    restart: always
    container_name: "rust01-api"
    env_file: .env
    volumes:
      - .:/usr/src/app
    tty: true

  rust01-db:
    image: postgres:16-bookworm
    container_name: rust01-db
    restart: unless-stopped
    ports:
      - 15433:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      timeout: 20s
      interval: 3s
      retries: 3

  rust01-db-migration:
    depends_on:
      rust01-db:
        condition: service_healthy
    build:
      context: db-migration
    container_name: rust01-db-migration
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db-migration:/root/migration
    entrypoint: ["/bin/sh", "scripts/migrate_local.sh"]
    command: up

volumes:
  db-data:
