name: Deploy

on:
  push:
    branches:
      - main

env:
  ARTIFACT_HOST: ${{ vars.ARTIFACT_HOST }}
  APP_IMAGE_NAME: ${{ vars.ARTIFACT_HOST }}/${{ secrets.GCP_PROJECT_ID }}/${{ vars.ARTIFACT_REPO }}/${{ vars.SERVICE_NAME }}:${{ github.sha }}
  MIGRATION_IMAGE_NAME: ${{ vars.ARTIFACT_HOST }}/${{ secrets.GCP_PROJECT_ID }}/${{ vars.ARTIFACT_REPO }}/${{ vars.MIGRATION_SERVICE_NAME }}:${{ github.sha }}

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure docker for artifact registry
        run: |
          gcloud auth configure-docker ${{ env.ARTIFACT_HOST }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push App image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.APP_IMAGE_NAME }}
          target: runtime

      - name: Build and push Migration image
        uses: docker/build-push-action@v5
        with:
          context: ./db-migration
          push: true
          tags: ${{ env.MIGRATION_IMAGE_NAME }}
